image:
  tag: v0.1.3

replicas: 1

service:
  type: NodePort
  port: 80
  targetPort: 8079
  NodePort: 30001

ingress:
  host: shop.34.88.81.253.nip.io
  secretName: shop.34.88.81.253.nip.io
  clusterIssuer: "letsencrypt-prod"

